name: swiftarrapi
description: Back-end API for connecting to Swiftarr
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0-35.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
